server:
  port: 8880
spring:
  application:
    name: eureka
  jooq:
    sql-dialect: MYSQL
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#    enabled: false
    service-url:
      defaultZone: http://localhost:8880/eureka
  instance:
    prefer-ip-address: true
#    appname: eureka
  server:
    enable-self-preservation: false
    peer-eureka-status-refresh-time-interval-ms: 10000





#  dashboard:
#  enabled: false