/*
 * This file is generated by jOOQ.
*/
package com.zipHandle.dao.test;


import com.zipHandle.dao.test.tables.MsdsDisplayCategory;
import com.zipHandle.dao.test.tables.Test;
import com.zipHandle.dao.test.tables.records.MsdsDisplayCategoryRecord;
import com.zipHandle.dao.test.tables.records.TestRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>test</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MsdsDisplayCategoryRecord> KEY_MSDS_DISPLAY_CATEGORY_PRIMARY = UniqueKeys0.KEY_MSDS_DISPLAY_CATEGORY_PRIMARY;
    public static final UniqueKey<MsdsDisplayCategoryRecord> KEY_MSDS_DISPLAY_CATEGORY_IDX_DISPLAY_CATEGORY_ID = UniqueKeys0.KEY_MSDS_DISPLAY_CATEGORY_IDX_DISPLAY_CATEGORY_ID;
    public static final UniqueKey<TestRecord> KEY_TEST_PRIMARY = UniqueKeys0.KEY_TEST_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MsdsDisplayCategoryRecord> KEY_MSDS_DISPLAY_CATEGORY_PRIMARY = createUniqueKey(MsdsDisplayCategory.MSDS_DISPLAY_CATEGORY, "KEY_msds_display_category_PRIMARY", MsdsDisplayCategory.MSDS_DISPLAY_CATEGORY.ID);
        public static final UniqueKey<MsdsDisplayCategoryRecord> KEY_MSDS_DISPLAY_CATEGORY_IDX_DISPLAY_CATEGORY_ID = createUniqueKey(MsdsDisplayCategory.MSDS_DISPLAY_CATEGORY, "KEY_msds_display_category_idx_display_category_id", MsdsDisplayCategory.MSDS_DISPLAY_CATEGORY.ID);
        public static final UniqueKey<TestRecord> KEY_TEST_PRIMARY = createUniqueKey(Test.TEST_, "KEY_test_PRIMARY", Test.TEST_.ID);
    }
}
