/*
 * This file is generated by jOOQ.
*/
package com.zipHandle.dao.test;


import com.zipHandle.dao.test.tables.MsdsDisplayCategory;
import com.zipHandle.dao.test.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.msds_display_category</code>.
     */
    public static final MsdsDisplayCategory MSDS_DISPLAY_CATEGORY = com.zipHandle.dao.test.tables.MsdsDisplayCategory.MSDS_DISPLAY_CATEGORY;

    /**
     * The table <code>test.test</code>.
     */
    public static final Test TEST_ = com.zipHandle.dao.test.tables.Test.TEST_;
}
