/*
 * This file is generated by jOOQ.
*/
package com.zipHandle.dao.mysql.tables.records;


import com.zipHandle.dao.mysql.tables.SlaveRelayLogInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * Relay Log Information
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaveRelayLogInfoRecord extends UpdatableRecordImpl<SlaveRelayLogInfoRecord> implements Record8<UInteger, String, ULong, String, ULong, Integer, UInteger, UInteger> {

    private static final long serialVersionUID = 2100541395;

    /**
     * Setter for <code>mysql.slave_relay_log_info.Number_of_lines</code>. Number of lines in the file or rows in the table. Used to version table definitions.
     */
    public void setNumberOfLines(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Number_of_lines</code>. Number of lines in the file or rows in the table. Used to version table definitions.
     */
    public UInteger getNumberOfLines() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Relay_log_name</code>. The name of the current relay log file.
     */
    public void setRelayLogName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Relay_log_name</code>. The name of the current relay log file.
     */
    public String getRelayLogName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Relay_log_pos</code>. The relay log position of the last executed event.
     */
    public void setRelayLogPos(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Relay_log_pos</code>. The relay log position of the last executed event.
     */
    public ULong getRelayLogPos() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Master_log_name</code>. The name of the master binary log file from which the events in the relay log file were read.
     */
    public void setMasterLogName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Master_log_name</code>. The name of the master binary log file from which the events in the relay log file were read.
     */
    public String getMasterLogName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Master_log_pos</code>. The master log position of the last executed event.
     */
    public void setMasterLogPos(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Master_log_pos</code>. The master log position of the last executed event.
     */
    public ULong getMasterLogPos() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Sql_delay</code>. The number of seconds that the slave must lag behind the master.
     */
    public void setSqlDelay(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Sql_delay</code>. The number of seconds that the slave must lag behind the master.
     */
    public Integer getSqlDelay() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Number_of_workers</code>.
     */
    public void setNumberOfWorkers(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Number_of_workers</code>.
     */
    public UInteger getNumberOfWorkers() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>mysql.slave_relay_log_info.Id</code>. Internal Id that uniquely identifies this record.
     */
    public void setId(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>mysql.slave_relay_log_info.Id</code>. Internal Id that uniquely identifies this record.
     */
    public UInteger getId() {
        return (UInteger) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, ULong, String, ULong, Integer, UInteger, UInteger> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, ULong, String, ULong, Integer, UInteger, UInteger> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.NUMBER_OF_LINES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.RELAY_LOG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.RELAY_LOG_POS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.MASTER_LOG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.MASTER_LOG_POS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.SQL_DELAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.NUMBER_OF_WORKERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getNumberOfLines();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRelayLogName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getRelayLogPos();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMasterLogName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getMasterLogPos();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSqlDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getNumberOfWorkers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value1(UInteger value) {
        setNumberOfLines(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value2(String value) {
        setRelayLogName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value3(ULong value) {
        setRelayLogPos(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value4(String value) {
        setMasterLogName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value5(ULong value) {
        setMasterLogPos(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value6(Integer value) {
        setSqlDelay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value7(UInteger value) {
        setNumberOfWorkers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord value8(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfoRecord values(UInteger value1, String value2, ULong value3, String value4, ULong value5, Integer value6, UInteger value7, UInteger value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SlaveRelayLogInfoRecord
     */
    public SlaveRelayLogInfoRecord() {
        super(SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO);
    }

    /**
     * Create a detached, initialised SlaveRelayLogInfoRecord
     */
    public SlaveRelayLogInfoRecord(UInteger numberOfLines, String relayLogName, ULong relayLogPos, String masterLogName, ULong masterLogPos, Integer sqlDelay, UInteger numberOfWorkers, UInteger id) {
        super(SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO);

        set(0, numberOfLines);
        set(1, relayLogName);
        set(2, relayLogPos);
        set(3, masterLogName);
        set(4, masterLogPos);
        set(5, sqlDelay);
        set(6, numberOfWorkers);
        set(7, id);
    }
}
