/*
 * This file is generated by jOOQ.
*/
package com.zipHandle.dao.mysql;


import com.zipHandle.dao.DefaultCatalog;
import com.zipHandle.dao.mysql.tables.ColumnsPriv;
import com.zipHandle.dao.mysql.tables.Db;
import com.zipHandle.dao.mysql.tables.Event;
import com.zipHandle.dao.mysql.tables.Func;
import com.zipHandle.dao.mysql.tables.GeneralLog;
import com.zipHandle.dao.mysql.tables.HelpCategory;
import com.zipHandle.dao.mysql.tables.HelpKeyword;
import com.zipHandle.dao.mysql.tables.HelpRelation;
import com.zipHandle.dao.mysql.tables.HelpTopic;
import com.zipHandle.dao.mysql.tables.InnodbIndexStats;
import com.zipHandle.dao.mysql.tables.InnodbTableStats;
import com.zipHandle.dao.mysql.tables.NdbBinlogIndex;
import com.zipHandle.dao.mysql.tables.Plugin;
import com.zipHandle.dao.mysql.tables.Proc;
import com.zipHandle.dao.mysql.tables.ProcsPriv;
import com.zipHandle.dao.mysql.tables.ProxiesPriv;
import com.zipHandle.dao.mysql.tables.Servers;
import com.zipHandle.dao.mysql.tables.SlaveMasterInfo;
import com.zipHandle.dao.mysql.tables.SlaveRelayLogInfo;
import com.zipHandle.dao.mysql.tables.SlaveWorkerInfo;
import com.zipHandle.dao.mysql.tables.SlowLog;
import com.zipHandle.dao.mysql.tables.TablesPriv;
import com.zipHandle.dao.mysql.tables.TimeZone;
import com.zipHandle.dao.mysql.tables.TimeZoneLeapSecond;
import com.zipHandle.dao.mysql.tables.TimeZoneName;
import com.zipHandle.dao.mysql.tables.TimeZoneTransition;
import com.zipHandle.dao.mysql.tables.TimeZoneTransitionType;
import com.zipHandle.dao.mysql.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mysql extends SchemaImpl {

    private static final long serialVersionUID = 174212739;

    /**
     * The reference instance of <code>mysql</code>
     */
    public static final Mysql MYSQL = new Mysql();

    /**
     * Column privileges
     */
    public final ColumnsPriv COLUMNS_PRIV = com.zipHandle.dao.mysql.tables.ColumnsPriv.COLUMNS_PRIV;

    /**
     * Database privileges
     */
    public final Db DB = com.zipHandle.dao.mysql.tables.Db.DB;

    /**
     * Events
     */
    public final Event EVENT = com.zipHandle.dao.mysql.tables.Event.EVENT;

    /**
     * User defined functions
     */
    public final Func FUNC = com.zipHandle.dao.mysql.tables.Func.FUNC;

    /**
     * General log
     */
    public final GeneralLog GENERAL_LOG = com.zipHandle.dao.mysql.tables.GeneralLog.GENERAL_LOG;

    /**
     * help categories
     */
    public final HelpCategory HELP_CATEGORY = com.zipHandle.dao.mysql.tables.HelpCategory.HELP_CATEGORY;

    /**
     * help keywords
     */
    public final HelpKeyword HELP_KEYWORD = com.zipHandle.dao.mysql.tables.HelpKeyword.HELP_KEYWORD;

    /**
     * keyword-topic relation
     */
    public final HelpRelation HELP_RELATION = com.zipHandle.dao.mysql.tables.HelpRelation.HELP_RELATION;

    /**
     * help topics
     */
    public final HelpTopic HELP_TOPIC = com.zipHandle.dao.mysql.tables.HelpTopic.HELP_TOPIC;

    /**
     * The table <code>mysql.innodb_index_stats</code>.
     */
    public final InnodbIndexStats INNODB_INDEX_STATS = com.zipHandle.dao.mysql.tables.InnodbIndexStats.INNODB_INDEX_STATS;

    /**
     * The table <code>mysql.innodb_table_stats</code>.
     */
    public final InnodbTableStats INNODB_TABLE_STATS = com.zipHandle.dao.mysql.tables.InnodbTableStats.INNODB_TABLE_STATS;

    /**
     * The table <code>mysql.ndb_binlog_index</code>.
     */
    public final NdbBinlogIndex NDB_BINLOG_INDEX = com.zipHandle.dao.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX;

    /**
     * MySQL plugins
     */
    public final Plugin PLUGIN = com.zipHandle.dao.mysql.tables.Plugin.PLUGIN;

    /**
     * Stored Procedures
     */
    public final Proc PROC = com.zipHandle.dao.mysql.tables.Proc.PROC;

    /**
     * Procedure privileges
     */
    public final ProcsPriv PROCS_PRIV = com.zipHandle.dao.mysql.tables.ProcsPriv.PROCS_PRIV;

    /**
     * User proxy privileges
     */
    public final ProxiesPriv PROXIES_PRIV = com.zipHandle.dao.mysql.tables.ProxiesPriv.PROXIES_PRIV;

    /**
     * MySQL Foreign Servers table
     */
    public final Servers SERVERS = com.zipHandle.dao.mysql.tables.Servers.SERVERS;

    /**
     * Master Information
     */
    public final SlaveMasterInfo SLAVE_MASTER_INFO = com.zipHandle.dao.mysql.tables.SlaveMasterInfo.SLAVE_MASTER_INFO;

    /**
     * Relay Log Information
     */
    public final SlaveRelayLogInfo SLAVE_RELAY_LOG_INFO = com.zipHandle.dao.mysql.tables.SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO;

    /**
     * Worker Information
     */
    public final SlaveWorkerInfo SLAVE_WORKER_INFO = com.zipHandle.dao.mysql.tables.SlaveWorkerInfo.SLAVE_WORKER_INFO;

    /**
     * Slow log
     */
    public final SlowLog SLOW_LOG = com.zipHandle.dao.mysql.tables.SlowLog.SLOW_LOG;

    /**
     * Table privileges
     */
    public final TablesPriv TABLES_PRIV = com.zipHandle.dao.mysql.tables.TablesPriv.TABLES_PRIV;

    /**
     * Time zones
     */
    public final TimeZone TIME_ZONE = com.zipHandle.dao.mysql.tables.TimeZone.TIME_ZONE;

    /**
     * Leap seconds information for time zones
     */
    public final TimeZoneLeapSecond TIME_ZONE_LEAP_SECOND = com.zipHandle.dao.mysql.tables.TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND;

    /**
     * Time zone names
     */
    public final TimeZoneName TIME_ZONE_NAME = com.zipHandle.dao.mysql.tables.TimeZoneName.TIME_ZONE_NAME;

    /**
     * Time zone transitions
     */
    public final TimeZoneTransition TIME_ZONE_TRANSITION = com.zipHandle.dao.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION;

    /**
     * Time zone transition types
     */
    public final TimeZoneTransitionType TIME_ZONE_TRANSITION_TYPE = com.zipHandle.dao.mysql.tables.TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE;

    /**
     * Users and global privileges
     */
    public final User USER = com.zipHandle.dao.mysql.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Mysql() {
        super("mysql", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ColumnsPriv.COLUMNS_PRIV,
            Db.DB,
            Event.EVENT,
            Func.FUNC,
            GeneralLog.GENERAL_LOG,
            HelpCategory.HELP_CATEGORY,
            HelpKeyword.HELP_KEYWORD,
            HelpRelation.HELP_RELATION,
            HelpTopic.HELP_TOPIC,
            InnodbIndexStats.INNODB_INDEX_STATS,
            InnodbTableStats.INNODB_TABLE_STATS,
            NdbBinlogIndex.NDB_BINLOG_INDEX,
            Plugin.PLUGIN,
            Proc.PROC,
            ProcsPriv.PROCS_PRIV,
            ProxiesPriv.PROXIES_PRIV,
            Servers.SERVERS,
            SlaveMasterInfo.SLAVE_MASTER_INFO,
            SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO,
            SlaveWorkerInfo.SLAVE_WORKER_INFO,
            SlowLog.SLOW_LOG,
            TablesPriv.TABLES_PRIV,
            TimeZone.TIME_ZONE,
            TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND,
            TimeZoneName.TIME_ZONE_NAME,
            TimeZoneTransition.TIME_ZONE_TRANSITION,
            TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE,
            User.USER);
    }
}
