/*
 * This file is generated by jOOQ.
*/
package com.zipHandle.dao.test.tables;


import com.zipHandle.dao.test.Keys;
import com.zipHandle.dao.test.Test;
import com.zipHandle.dao.test.tables.records.MsdsDisplayCategoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MsdsDisplayCategory extends TableImpl<MsdsDisplayCategoryRecord> {

    private static final long serialVersionUID = 558595082;

    /**
     * The reference instance of <code>test.msds_display_category</code>
     */
    public static final MsdsDisplayCategory MSDS_DISPLAY_CATEGORY = new MsdsDisplayCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MsdsDisplayCategoryRecord> getRecordType() {
        return MsdsDisplayCategoryRecord.class;
    }

    /**
     * The column <code>test.msds_display_category.id</code>. 展示类目ID
     */
    public final TableField<MsdsDisplayCategoryRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "展示类目ID");

    /**
     * The column <code>test.msds_display_category.parent_cid</code>. 父类目ID=0时，代表的是一级的类目
     */
    public final TableField<MsdsDisplayCategoryRecord, String> PARENT_CID = createField("parent_cid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "父类目ID=0时，代表的是一级的类目");

    /**
     * The column <code>test.msds_display_category.top_cid</code>. 顶级类目 编号
     */
    public final TableField<MsdsDisplayCategoryRecord, String> TOP_CID = createField("top_cid", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "顶级类目 编号");

    /**
     * The column <code>test.msds_display_category.display_name</code>. 类目名称
     */
    public final TableField<MsdsDisplayCategoryRecord, String> DISPLAY_NAME = createField("display_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "类目名称");

    /**
     * The column <code>test.msds_display_category.is_parent</code>. 该类目是否为父类目(即：该类目是否还有子类目)
     */
    public final TableField<MsdsDisplayCategoryRecord, Integer> IS_PARENT = createField("is_parent", org.jooq.impl.SQLDataType.INTEGER, this, "该类目是否为父类目(即：该类目是否还有子类目)");

    /**
     * The column <code>test.msds_display_category.is_bottom</code>. 是否是末级分类
     */
    public final TableField<MsdsDisplayCategoryRecord, Integer> IS_BOTTOM = createField("is_bottom", org.jooq.impl.SQLDataType.INTEGER, this, "是否是末级分类");

    /**
     * The column <code>test.msds_display_category.status</code>. 状态
     */
    public final TableField<MsdsDisplayCategoryRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "状态");

    /**
     * The column <code>test.msds_display_category.orders</code>. 排序
     */
    public final TableField<MsdsDisplayCategoryRecord, Integer> ORDERS = createField("orders", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "排序");

    /**
     * The column <code>test.msds_display_category.create_user</code>. 创建人
     */
    public final TableField<MsdsDisplayCategoryRecord, String> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "创建人");

    /**
     * The column <code>test.msds_display_category.create_date</code>. 创建时间
     */
    public final TableField<MsdsDisplayCategoryRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>test.msds_display_category.modify_user</code>. 修改人
     */
    public final TableField<MsdsDisplayCategoryRecord, String> MODIFY_USER = createField("modify_user", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "修改人");

    /**
     * The column <code>test.msds_display_category.modify_date</code>. 修改时间
     */
    public final TableField<MsdsDisplayCategoryRecord, Timestamp> MODIFY_DATE = createField("modify_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>test.msds_display_category.isdelete</code>. 是否是逻辑删除（0为否，1为是，默认为0）
     */
    public final TableField<MsdsDisplayCategoryRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否是逻辑删除（0为否，1为是，默认为0）");

    /**
     * The column <code>test.msds_display_category.level</code>. 分类相对于顶级分类的等级
     */
    public final TableField<MsdsDisplayCategoryRecord, Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this, "分类相对于顶级分类的等级");

    /**
     * The column <code>test.msds_display_category.only_code</code>.
     */
    public final TableField<MsdsDisplayCategoryRecord, String> ONLY_CODE = createField("only_code", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

    /**
     * The column <code>test.msds_display_category.modify_relations_date</code>.
     */
    public final TableField<MsdsDisplayCategoryRecord, Timestamp> MODIFY_RELATIONS_DATE = createField("modify_relations_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>test.msds_display_category.tree_path</code>.
     */
    public final TableField<MsdsDisplayCategoryRecord, String> TREE_PATH = createField("tree_path", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>test.msds_display_category.is_hidden</code>. 是否隐藏(0隐藏1显示)
     */
    public final TableField<MsdsDisplayCategoryRecord, Boolean> IS_HIDDEN = createField("is_hidden", org.jooq.impl.SQLDataType.BIT.defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "是否隐藏(0隐藏1显示)");

    /**
     * The column <code>test.msds_display_category.platform</code>.
     */
    public final TableField<MsdsDisplayCategoryRecord, String> PLATFORM = createField("platform", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>test.msds_display_category</code> table reference
     */
    public MsdsDisplayCategory() {
        this("msds_display_category", null);
    }

    /**
     * Create an aliased <code>test.msds_display_category</code> table reference
     */
    public MsdsDisplayCategory(String alias) {
        this(alias, MSDS_DISPLAY_CATEGORY);
    }

    private MsdsDisplayCategory(String alias, Table<MsdsDisplayCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private MsdsDisplayCategory(String alias, Table<MsdsDisplayCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MsdsDisplayCategoryRecord> getPrimaryKey() {
        return Keys.KEY_MSDS_DISPLAY_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MsdsDisplayCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<MsdsDisplayCategoryRecord>>asList(Keys.KEY_MSDS_DISPLAY_CATEGORY_PRIMARY, Keys.KEY_MSDS_DISPLAY_CATEGORY_IDX_DISPLAY_CATEGORY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsdsDisplayCategory as(String alias) {
        return new MsdsDisplayCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MsdsDisplayCategory rename(String name) {
        return new MsdsDisplayCategory(name, null);
    }
}
